---
ansible_inentory_path: production

gatus_slug: "(Production DevOps)"

postgres_db_backup_enabled: true
postgres_db_k8s_namespace: "authentik"
postgres_db_k8s_selector: "app.kubernetes.io/name=postgresql,app.kubernetes.io/component=primary"
postgres_db_name: authentik
postgres_db_user: authentik
postgres_db_password: "{{ lookup('env','AUTHENTIK_POSTGRESQL_PASSWORD') }}"

terraform_output_config_node: "roland"
terraform_output_tf_dir: "/home/lab/gitops-homelab/terraform/environments/production-k8s"
