gatus_slug: "(Production Dev Ops)"

s3_backup_remote_user: allan
s3_backup_remote_path: "/mnt/pool1/gitops-homelab/s3-backups/"
s3_backup_remote_host_ip: "{{ hostvars['procyon'].ansible_host }}"
s3_backup_buckets:
  - allans-home-lab-longhorn
  - allans-homelab-terraform-state-bucket
  - gitops-homelab-longhorn
  - gitops-homelab-longhorn-attic
  - gitops-homelab-longhorn-staging
  - gitops-homelab-terraform

terraform_output_tf_dir: "/home/lab/gitops-homelab/terraform/environments/production-k8s"