---
all:
  hosts:
    #### NEW HOSTS
    ## BARE METAL
    christine:
      ansible_host: 192.168.86.212 
    derry:
      ansible_host: 192.168.86.210
    flagg:
      ansible_host: 192.168.86.205
    gan:
      ansible_host: 192.168.86.211
    maturin:
      ansible_host: 192.168.86.200
    shardik:
      ansible_host: 192.168.86.201
    tak: # mac laptop using dhcp
    ## VIRTUAL MACHINES
    carrie:
      ansible_host: 192.168.86.228
    misery:
      ansible_host: 192.168.86.227
    sheemie:
      ansible_host: 192.168.86.229
    ## ORCHESTRATOR VIRTUAL MACHINES
    blaine:
      ansible_host: 192.168.86.223
      gatus_slug: "(OpenVPN Gateway)"
    patricia:
      ansible_host: 192.168.86.224
      gatus_slug: "(Media Acquisition)"
    langolier:
      ansible_host: 192.168.86.216
      gatus_slug: "(DevOps)"
    cujo:
      ansible_host: 192.168.86.217
    todash:
      ansible_host: 192.168.86.218
      gatus_slug: "(Ubuntu Sandbox)"
    ## KUBERNETES
    roland:
      ansible_host: 192.168.86.151 
    eddie:
      ansible_host: 192.168.86.152
    jake:
      ansible_host: 192.168.86.153
    susannah:
      ansible_host: 192.168.86.154
    ## OFF PREMISES
    gilead:
      ansible_host: 100.95.108.6
    #### OLD HOSTS
    antares:
      ansible_host: 192.168.86.167
    arcturus:
      ansible_host: 192.168.86.124 
    deneb:
      ansible_host: 192.168.86.166
    polaris:
      ansible_host: 192.168.86.101
    procyon:
      ansible_host: 192.168.86.106
    sirius:
      ansible_host: 192.168.86.105
  children:
    talos:
      children:
        talos_controlplanes:
          hosts:
            roland:
        talos_workers:
          hosts:
            eddie:
            jake:
            susannah:
    ubuntu:
      hosts:
        sheemie:
      children:
        docker:
          children:
            docker_cloudflare:
              hosts:
                flagg:
            docker_gatus:
              hosts:
                flagg:
            docker_immich:
              hosts:
                misery:
            docker_it_tools:
              hosts:
                carrie:
            docker_jellyfin:
              hosts:
                misery:
            # docker_media_acquisition:
            #   hosts:
            #     cujo:
            docker_monitoring:
              hosts:
                carrie:
                # cujo:
                flagg:
                misery:
                sheemie:
            docker_ngb:
              hosts:
                carrie:
            docker_pihole:
              hosts:
                flagg:
            docker_plex:
              hosts:
                misery:
            docker_tautulli:
              hosts:
                misery:
            docker_traefik:
              hosts:
                flagg:
            docker_twingate:
              hosts:
                flagg:
        # expressvpn:
        #   hosts:
        #     cujo:
        tailscale:
          hosts:
            flagg:
