preUpgradeChecker:
  jobEnabled: false

global:
  tolerations:
    - key: "openvpn"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

defaultSettings:
  taintToleration: "openvpn=true:NoSchedule"

service:
  ui:
    type: LoadBalancer
    loadBalancerIP: "192.168.86.183"
