all:
  hosts:
    barlow:
      ansible_host: 192.168.86.225
    blaine:
      ansible_host: 192.168.86.98
      ansible_python_interpreter: "/usr/bin/python3"
    patricia:
      ansible_host: 192.168.86.99
      ansible_python_interpreter: "/usr/bin/python3"
    procyon: # needed for backups
      ansible_host: 192.168.86.106
  children:
    ubuntu:
      children:
        devops:
          hosts:
            barlow:
            blaine:
            patricia:
        docker:
          children:
            docker_monitoring:
              hosts:
                barlow:
